name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      POWERUP_NAME: My Power-Up
      POWERUP_ID: 0a000000aa0aa00aaaaaaaa0
      POWERUP_APP_KEY: 00a00a0a0aa000000a0000000aa0aa0a
      OPTRO_API_KEY: DISABLED
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Packages
        run: yarn install
      - name: Build GitHub Pages
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
